version: '3.4'
services:
  bot:
    build:
      context: .
      dockerfile: bot.dockerfile
    depends_on:
      - actions
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --credentials
      - credentials.yml
      - --debug


  actions:
    build:
      context: .
      dockerfile: actions.dockerfile
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions